export const dropsHelp = [
  'Enemy drop randomization can be toggled with the "d" switch. Drops may',
  'also be specified using argument syntax.',
  '',
  'Drops format:',
  '  d[:<enemy>[-<level>][:[<item>][-[<item>]]][:...]',
  '',
  'Enemies and items are specified by removing any non-alphanumeric',
  'characters from their name. Enemies with the same name can be dis-',
  'ambiguated by specifying their level.',
  '',
  'A wildcard character ("*") can be used to replace items for all enemies.',
  '',
  'The global drop table can be edited by specifying "Global" as the enemy',
  'name. Please note that there are 32 items in the global drop table.',
  '',
  'Examples:',
  '  d:Zombie:Cutlass-Bandanna   Zombie drops Cutlass and Bandanna',
  '  d:Slinger:-Orange           Replace Slinger rare drop with orange',
  '  d:MedusaHead-8:             Medusa Head level 8 drops nothing',
  '  d:*:Grapes-Potion           Every enemy drops Grapes and Potion',
  '  d:Global:Apple-Orange-Tart  Replace first 3 items in global drops table',
  '                              with Apple, Orange, and Tart',
  '',
  'Items can be prevented from being randomized to enemy\'s drop table by',
  'prefixing the enemy\'s name with a hyphen ("-"):',
  '  d:-AxeKnight:Stopwatch   Axe Knight never drops Stopwatch',
  '  d:-StoneRose:Medal-Opal  Stone Rose never drops Medal or Opal',
  '',
  'If other randomization options follow a drop, they must also be',
  'separated from the drop with a comma:',
  '  $0 --opt d:Slinger:-Orange,ipt',
].join('\n');
