import constants from '../../src/constants.mjs';

export const relicsHelp = [
  'Relic location randomization can be toggled with the "r" switch, and',
  'custom relic location locks may be specified using argument syntax.',
  '',
  'A relic location lock sets the abilities required to access a relic',
  'location. Each relic location may be guarded by multiple locks, and the',
  'location will be open to the player once they have all abilities',
  'comprising any single lock.',
  '',
  'A location can also specify escape requirements. These are combinations of',
  'abilities, any one of which must be satisified by all progression routes',
  'granting access to the location. This is intended to prevent the player',
  'from accessing an area that they might not have the ability to escape',
  'from. Note that is is possible for the location itself to grant one of the',
  'abilities required to escape from it.',
  '',
  'Relics format:',
  '  r[:[@]<location>[:<ability>[-<ability>...]]'
  + '[+<ability>[-<ability>...]]][:...]',
  '',
  'Relic locations and the abilities they provide are identified by one',
  'letter:',
  '  (' + constants.RELIC.SOUL_OF_BAT + ') Soul of Bat',
  '  (' + constants.RELIC.FIRE_OF_BAT + ') Fire of Bat',
  '  (' + constants.RELIC.ECHO_OF_BAT + ') Echo of Echo',
  '  (' + constants.RELIC.FORCE_OF_ECHO + ') Force of Echo',
  '  (' + constants.RELIC.SOUL_OF_WOLF + ') Soul of Wolf',
  '  (' + constants.RELIC.POWER_OF_WOLF + ') Power of Wolf',
  '  (' + constants.RELIC.SKILL_OF_WOLF + ') Skill of Wolf',
  '  (' + constants.RELIC.FORM_OF_MIST + ') Form of Mist',
  '  (' + constants.RELIC.POWER_OF_MIST + ') Power of Mist',
  '  (' + constants.RELIC.GAS_CLOUD + ') Gas Cloud',
  '  (' + constants.RELIC.CUBE_OF_ZOE + ') Cube of Zoe',
  '  (' + constants.RELIC.SPIRIT_ORB + ') Spirit Orb',
  '  (' + constants.RELIC.GRAVITY_BOOTS + ') Gravity Boots',
  '  (' + constants.RELIC.LEAP_STONE + ') Leap Stone',
  '  (' + constants.RELIC.HOLY_SYMBOL + ') Holy Symbol',
  '  (' + constants.RELIC.FAERIE_SCROLL + ') Faerie Scroll',
  '  (' + constants.RELIC.JEWEL_OF_OPEN + ') Jewel of Open',
  '  (' + constants.RELIC.MERMAN_STATUE + ') Merman Statue',
  '  (' + constants.RELIC.BAT_CARD + ') Bat Card',
  '  (' + constants.RELIC.GHOST_CARD + ') Ghost Card',
  '  (' + constants.RELIC.FAERIE_CARD + ') Faerie Card',
  '  (' + constants.RELIC.DEMON_CARD + ') Demon Card',
  '  (' + constants.RELIC.SWORD_CARD + ') Sword Card',
  '  (' + constants.RELIC.SPRITE_CARD + ') Sprite Card',
  '  (' + constants.RELIC.NOSEDEVIL_CARD + ') Nosedevil Card',
  '  (' + constants.RELIC.HEART_OF_VLAD + ') Heart of Vlad',
  '  (' + constants.RELIC.TOOTH_OF_VLAD + ') Tooth of Vlad',
  '  (' + constants.RELIC.RIB_OF_VLAD + ') Rib of Vlad',
  '  (' + constants.RELIC.RING_OF_VLAD + ') Ring of Vlad',
  '  (' + constants.RELIC.EYE_OF_VLAD + ') Eye of Vlad',
  '  (' + constants.RELIC.SPIKE_BREAKER + ') Spike Breaker',
  '  (' + constants.RELIC.SILVER_RING + ') Silver ring',
  '  (' + constants.RELIC.GOLD_RING + ') Gold ring',
  '  (' + constants.RELIC.HOLY_GLASSES + ') Holy glasses',
  '',
  'Examples:',
  '  r:B:L      Soul of Bat relic location requires only Leap Stone',
  '  r:y:LV-MP  Holy Symbol relic location requires Leap Stone + Gravity',
  '             Boots OR Form of Mist + Power of Mist',
  '',
  'Note that relic location extensions use the name of the item being',
  'replaced as their identifier:',
  '  r:Mormegil:JL-JV  Mormegil location requires Jewel of Open + Leap Stone',
  '                    OR Jewel of Open + Gravity Boots',
  '',
  'Escape requirements follow the ability locks and are separated by a "+":',
  '  r:H:GS+B-LV-MP  Holy Glasses location requires Gold + Silver Rings for',
  '                  access and Soul of Bat, Leap Stone + Gravity Boots, or',
  '                  Mist + Power of Mist for escape.',
  '',
  'Locks for different locations can be specified by separating each',
  'location by a colon:',
  '  r:B:L:y:LV-MP',
  '',
  'Relic locations extension can be specified with the letter "x". Extension',
  'will allow progression to be placed in locations that do not contain',
  'progression in the vanilla game.',
  '',
  'There are three extension modes:',
  '  guarded    Adds Crystal cloak, Mormegil, Dark Blade, and Ring of Arcana',
  '             to the location pool. This is the default extension mode when',
  '             when enabled without an argument.',
  '  spread     Based on guarded, and adds Dragon helm, Shotel, and Staurolite',
  '             to the location pool.',
  '  equipment  Adds remaining equipment tiles to the location pool.',
  '',
  'Extension format:',
  '  x:<mode>',
  '',
  'Examples:',
  '  r:x:guarded    Enables guarded extension mode',
  '  r:x:equipment  Enables equipment extension mode',
  '',
  'Additionally there are items to provide abilities that do not have a',
  'dedicated vanilla location.',
  '  (' + constants.RELIC.THRUST_SWORD + ') Thrust sword',
  '',
  'These ability items can be added to the relic placement logic by',
  'specifying their ability letter:',
  '  r:D:M:D-L  Enable Thrust sword placement and have Form of Mist location',
  '             require a Thrust sword or Leap Stone',
  '',
  'An optional complexity target can specify a set of abilities that are',
  'considered win conditions. A minimum and maximum complexity depth specify',
  'how many relics must be obtained in series to unlock a win condition:',
  '  r:3:LV-MP  Leap Stone + Gravity Boots OR Form of Mist + Power of Mist',
  '             required to complete seed with a minimum depth of .',
  '  r:3-5:SG   Silver + Gold ring required to complete seed with a minimum',
  '             depth of 3 and a maximum depth of 5',
  '',
  'Relics can be placed in an explicit location by prefixing a location with',
  'the "@" symbol. Multiple relics may be specified, however, only one will',
  'be selected for that location at the time of seed generation. Ability',
  'locks and placed relics may be freely mixed in together:',
  '  r:B:L:@B:fe  Soul of Bat location requires Leap Stone and may contain',
  '               either Fire of Bat or Force of Echo',
  '',
  'A placed relic location may also be "empty". To specify an empty location,',
  'include a "0" in the relic list for that location. Note that relic',
  'locations must be extended when allowing a location to be empty:',
  '  r:x:guarded:@B:0    Soul of Bat location is empty',
  '  r:x:guarded:@y:fe0  Holy Symbol location may be empty or contain Fire of',
  '                      Bat or Force of Echo',
  '',
  'Relics may be blocked from being randomized to a location by prefxing it',
  'with a hypen ("-"):',
  '  r:-J:0BLG  Never let Jewel of Open location be empty, or have Soul of',
  '             Bat, Leap Stone, or Gravity Boots',
  '',
  'A relic can be replaced with an arbitrary item by prefixing its ability',
  'with the "=" symbol:',
  '  r:=z:Duplicator  Replace Cube of Zoe with Duplicator',
  '',
  'Placing progression items in vanilla relic locations requires an item in',
  'that zone to be removed. A player may notice a removed item in a zone',
  'and correctly assume that a progression item has been randomized to a',
  'location in that zone. To prevent this leakage of information, the default',
  'behavior of the relic randomizer is to remove at most 3 random items from',
  'every zone containing relics. This behavior can be turned off by including',
  'the string "~r" as an argument:',
  '  r:~r  Disable leak prevention',
  '',
  'If other randomization options follow a lock, they must also be',
  'separated from the lock with a comma:',
  '  $0 --opt r:B:L:y:LG-MP,dpt',
].join('\n');
