export const writesHelp = [
  'Arbitrary data can be written using the "w" option with argument syntax.',
  '',
  'Write format:',
  '  w:address:value[:address:value[:...]]',
  '',
  'Addresses should be either decimal numbers or "0x"-prefixed hex strings.',
  '',
  'Values are either "0x"-prefixed hex strings or unprefixed hex strings.',
  'Use an unprefixed hex string to specify a string of bytes.',
  'Use a prefixed hex string to specify a number written as little-endian.',
  'The width of the number written is determined by the length of the hex.',
  'To write a character, the hex must be 2 characters. To write a short, the',
  'hex must be 4 characters. To write a word, the hex must be 8 characters.',
  'To write a long, the hex must be 16 characters. A prefixed hex string of',
  'any other character length is erroneous.',
  '',
  'Additionally, random data can be written by specifying a value of "rc" for',
  'a random character (1 byte), "rs" for a random short (2 bytes), "rw" for a',
  'random word (4 bytes), or "rl" for a random long (8 bytes).',
  '',
  'Examples:',
  '  w:0x04c590:0x00                Write the character 0x00 to the address',
  '                                 0x04c590',
  '  w:0x043930c4:0x78b4            Write the value 0x78b4 as a little-endian',
  '                                 short integer to the address 0x043930c4',
  '  w:0x032b08:0x08075180          Write the value 0x08075180 as a little-',
  '                                 endian integer to the address 0x032b08',
  '  w:0x0abb28:0x00:0x0abb2a:0x01  Write the characters 0x00 and 0x01 to the',
  '                                 addresses 0x0abb28 and 0x0abb2a',
  '                                 respectively',
  '  w:0x04389c6c:74657374ff        Write the string 74657374ff to the',
  '                                 address 0x04389c6c',
  '  w:0x04937fb4:rc                Write a random byte to the address',
  '                                 0x04937fb4',
  '  w:0x0456a274:rs                Write 2 random bytes to the address',
  '                                 0x0456a274',
  '  w:0x0456b888:rw                Write 4 random bytes to the address',
  '                                 0x0456b888',
  '  w:0x049f4a98:rl                Write 8 random bytes to the address',
  '                                 0x049f4a98',
  '',
  'If other randomization options follow a write, they must also be separated',
  'from the write with a comma:',
  '  $0 --opt w:0x0abb28:0x00:0x0abb2a:0x01,dpt',
].join('\n');
