const presets = [
    "casual",
    "safe",
    "adventure",
    "og",
    "guarded-og",
    "speedrun",
    "lycanthrope",
    "warlock",
    "nimble",
    "expedition",
    "bat-master",
    "glitch",
    "scavenger",
    "empty-hand",
    "gem-farmer",
    "third-castle",
    "rat-race",
    "magic-mirror",
    "leg-day",
    "boss-rush",
    "aperture",
    "big-toss",
    "bountyhunter",
    "bountyhunter-tc",
    "hitman",
    "chaos-lite",
    "beyond",
    "breach",
    "grand-tour",
    "crash-course",
    "forge",
    "lookingglass",
    "skinwalker",
    "summoner",
    "agonizetwtw",
    "stwosafe",
    "open"
];


export default presets;