const presets = [
    "adventure",
    "agonizetwtw",
    "aperture",
    "batMaster",
    "beyond",
    "bigToss",
    "bossRush",
    "bountyhunter",
    "bountyhunterTc",
    "breach",
    "casual",
    "chaosLite",
    "crashCourse",
    "emptyHand",
    "expedition",
    "forge",
    "gemFarmer",
    "glitch",
    "grandTour",
    "guardedOg",
    "hitman",
    "legDay",
    "lookingglass",
    "lycanthrope",
    "magicMirror",
    "nimble",
    "og",
    "open",
    "ratRace",
    "safe",
    "scavenger",
    "skinwalker",
    "speedrun",
    "stwosafe",
    "summoner",
    "thirdCastle",
    "warlock",
];


export default presets;